const recipeData = [
  {
    id: "tuna-mayo-rice",
    name: "참치마요덮밥",
    ingredients: ["밥", "참치캔", "마요네즈", "김"],
    optional: ["간장", "계란", "대파"],
    time: 5,
    calories: 620,
    difficulty: "매우 쉬움",
    dishLevel: "적음",
    tools: ["그릇", "숟가락"],
    tags: ["한그릇", "불안씀", "자취생", "10분이내", "초보자가능"],
    steps: ["밥 위에 기름 뺀 참치를 올립니다.", "마요네즈와 잘게 부순 김을 얹습니다.", "간장을 조금 더해 비벼 먹습니다."]
  },
  {
    id: "egg-soy-rice",
    name: "계란간장밥",
    ingredients: ["밥", "계란", "간장", "참기름"],
    optional: ["김", "대파", "후추"],
    time: 6,
    calories: 470,
    difficulty: "매우 쉬움",
    dishLevel: "적음",
    tools: ["프라이팬", "그릇", "숟가락"],
    tags: ["한그릇", "아침식사", "10분이내", "초보자가능"],
    steps: ["계란프라이를 만듭니다.", "밥 위에 계란, 간장, 참기름을 올립니다.", "취향에 따라 김이나 후추를 더합니다."]
  },
  {
    id: "kimchi-fried-rice",
    name: "김치볶음밥",
    ingredients: ["밥", "김치", "식용유"],
    optional: ["계란", "스팸", "대파", "참기름"],
    time: 10,
    calories: 520,
    difficulty: "쉬움",
    dishLevel: "보통",
    tools: ["프라이팬", "주걱"],
    tags: ["한그릇", "자취생", "10분이내", "초보자가능"],
    steps: ["기름을 두르고 김치를 먼저 볶습니다.", "밥을 넣고 고루 볶습니다.", "참기름이나 계란프라이를 곁들입니다."]
  },
  {
    id: "spam-mayo-rice",
    name: "스팸마요덮밥",
    ingredients: ["밥", "스팸", "마요네즈"],
    optional: ["계란", "김", "간장"],
    time: 9,
    calories: 760,
    difficulty: "쉬움",
    dishLevel: "보통",
    tools: ["프라이팬", "그릇"],
    tags: ["한그릇", "자취생", "10분이내", "초보자가능"],
    steps: ["스팸을 작게 썰어 노릇하게 굽습니다.", "밥 위에 스팸과 마요네즈를 올립니다.", "김이나 계란을 곁들이면 더 든든합니다."]
  },
  {
    id: "soy-egg-fried-rice",
    name: "간장계란볶음밥",
    ingredients: ["밥", "계란", "간장", "식용유"],
    optional: ["대파", "후추", "참기름"],
    time: 8,
    calories: 540,
    difficulty: "쉬움",
    dishLevel: "보통",
    tools: ["프라이팬", "주걱"],
    tags: ["한그릇", "아침식사", "10분이내", "초보자가능"],
    steps: ["기름에 계란을 스크램블처럼 볶습니다.", "밥과 간장을 넣고 빠르게 볶습니다.", "후추나 참기름으로 마무리합니다."]
  },
  {
    id: "tuna-kimchi-fried-rice",
    name: "참치김치볶음밥",
    ingredients: ["밥", "참치캔", "김치", "식용유"],
    optional: ["계란", "대파", "참기름"],
    time: 10,
    calories: 640,
    difficulty: "쉬움",
    dishLevel: "보통",
    tools: ["프라이팬", "주걱"],
    tags: ["한그릇", "자취생", "10분이내"],
    steps: ["김치를 먼저 볶아 신맛을 날립니다.", "참치와 밥을 넣고 볶습니다.", "참기름을 살짝 둘러 마무리합니다."]
  },
  {
    id: "butter-soy-rice",
    name: "버터간장밥",
    ingredients: ["밥", "버터", "간장"],
    optional: ["계란", "김", "후추"],
    time: 4,
    calories: 450,
    difficulty: "매우 쉬움",
    dishLevel: "적음",
    tools: ["그릇", "숟가락"],
    tags: ["한그릇", "불안씀", "아침식사", "10분이내", "초보자가능"],
    steps: ["따뜻한 밥에 버터를 올려 녹입니다.", "간장을 조금 넣고 비빕니다.", "김이나 계란을 더하면 맛이 좋아집니다."]
  },
  {
    id: "mandu-rice-bowl",
    name: "만두덮밥",
    ingredients: ["밥", "만두", "간장"],
    optional: ["계란", "대파", "참기름"],
    time: 10,
    calories: 650,
    difficulty: "쉬움",
    dishLevel: "보통",
    tools: ["프라이팬", "그릇"],
    tags: ["한그릇", "자취생", "10분이내", "초보자가능"],
    steps: ["만두를 굽거나 데운 뒤 잘게 자릅니다.", "밥 위에 만두를 올립니다.", "간장과 참기름을 더해 비빕니다."]
  },
  {
    id: "tofu-rice-bowl",
    name: "두부덮밥",
    ingredients: ["밥", "두부", "간장"],
    optional: ["대파", "고춧가루", "참기름"],
    time: 8,
    calories: 430,
    difficulty: "매우 쉬움",
    dishLevel: "적음",
    tools: ["그릇", "숟가락"],
    tags: ["한그릇", "설거지적음", "아침식사", "10분이내", "초보자가능"],
    steps: ["두부를 으깨 밥 위에 올립니다.", "간장과 참기름을 넣습니다.", "대파나 고춧가루를 더해 비빕니다."]
  },
  {
    id: "sausage-fried-rice",
    name: "소시지볶음밥",
    ingredients: ["밥", "소시지", "식용유"],
    optional: ["양파", "대파", "계란", "케첩"],
    time: 10,
    calories: 690,
    difficulty: "쉬움",
    dishLevel: "보통",
    tools: ["프라이팬", "주걱"],
    tags: ["한그릇", "자취생", "10분이내"],
    steps: ["소시지를 얇게 썰어 볶습니다.", "밥을 넣고 함께 볶습니다.", "케첩이나 계란을 곁들입니다."]
  },
  {
    id: "egg-ramen",
    name: "계란라면",
    ingredients: ["라면", "계란"],
    optional: ["대파", "김치", "치즈"],
    time: 7,
    calories: 590,
    difficulty: "매우 쉬움",
    dishLevel: "보통",
    tools: ["냄비", "젓가락"],
    tags: ["야식", "10분이내", "초보자가능"],
    steps: ["라면을 평소처럼 끓입니다.", "면이 익을 때 계란을 넣습니다.", "대파를 올려 마무리합니다."]
  },
  {
    id: "cheese-ramen",
    name: "치즈라면",
    ingredients: ["라면", "치즈"],
    optional: ["계란", "대파", "김치"],
    time: 7,
    calories: 650,
    difficulty: "매우 쉬움",
    dishLevel: "보통",
    tools: ["냄비", "젓가락"],
    tags: ["야식", "10분이내", "초보자가능"],
    steps: ["라면을 끓입니다.", "불을 끄기 직전에 치즈를 올립니다.", "치즈가 녹으면 바로 먹습니다."]
  },
  {
    id: "fried-ramen",
    name: "볶음라면",
    ingredients: ["라면", "식용유"],
    optional: ["계란", "양파", "대파", "굴소스"],
    time: 10,
    calories: 560,
    difficulty: "쉬움",
    dishLevel: "보통",
    tools: ["냄비", "프라이팬"],
    tags: ["야식", "10분이내", "자취생"],
    steps: ["면을 살짝 덜 익게 삶아 물기를 뺍니다.", "팬에 기름을 두르고 면을 볶습니다.", "스프를 조금 넣어 간을 맞춥니다."]
  },
  {
    id: "tuna-bibim-noodle",
    name: "참치비빔면",
    ingredients: ["라면", "참치캔", "고추장"],
    optional: ["상추", "김", "참기름"],
    time: 10,
    calories: 620,
    difficulty: "쉬움",
    dishLevel: "보통",
    tools: ["냄비", "그릇"],
    tags: ["야식", "10분이내", "자취생"],
    steps: ["라면 면만 삶아 찬물에 헹굽니다.", "고추장과 참기름으로 양념합니다.", "참치를 올려 비빕니다."]
  },
  {
    id: "soy-bibim-noodle",
    name: "간장비빔국수",
    ingredients: ["국수", "간장", "참기름"],
    optional: ["설탕", "김", "계란"],
    time: 10,
    calories: 460,
    difficulty: "쉬움",
    dishLevel: "적음",
    tools: ["냄비", "그릇"],
    tags: ["한그릇", "10분이내", "초보자가능"],
    steps: ["국수를 삶아 찬물에 헹굽니다.", "간장, 참기름, 설탕을 섞습니다.", "국수에 양념을 넣고 비빕니다."]
  },
  {
    id: "gochujang-bibim-noodle",
    name: "고추장비빔국수",
    ingredients: ["국수", "고추장", "참기름"],
    optional: ["설탕", "상추", "김치"],
    time: 10,
    calories: 480,
    difficulty: "쉬움",
    dishLevel: "적음",
    tools: ["냄비", "그릇"],
    tags: ["한그릇", "야식", "10분이내", "초보자가능"],
    steps: ["국수를 삶아 찬물에 헹굽니다.", "고추장, 참기름, 설탕을 섞습니다.", "채소나 김치를 올려 비빕니다."]
  },
  {
    id: "ramen-porridge",
    name: "라면죽",
    ingredients: ["라면", "밥"],
    optional: ["계란", "대파", "김"],
    time: 9,
    calories: 680,
    difficulty: "매우 쉬움",
    dishLevel: "보통",
    tools: ["냄비", "숟가락"],
    tags: ["한그릇", "야식", "10분이내", "초보자가능"],
    steps: ["라면을 잘게 부숴 끓입니다.", "밥을 넣고 걸쭉하게 끓입니다.", "계란을 풀어 넣으면 더 부드럽습니다."]
  },
  {
    id: "pan-fried-tofu",
    name: "두부부침",
    ingredients: ["두부", "식용유", "간장"],
    optional: ["대파", "고춧가루", "참기름"],
    time: 10,
    calories: 270,
    difficulty: "쉬움",
    dishLevel: "보통",
    tools: ["프라이팬", "접시"],
    tags: ["술안주", "10분이내", "초보자가능"],
    steps: ["두부 물기를 닦고 먹기 좋게 썹니다.", "팬에 노릇하게 부칩니다.", "간장 양념을 곁들입니다."]
  },
  {
    id: "rolled-egg",
    name: "계란말이",
    ingredients: ["계란", "소금", "식용유"],
    optional: ["대파", "당근", "치즈"],
    time: 10,
    calories: 260,
    difficulty: "보통",
    dishLevel: "보통",
    tools: ["프라이팬", "젓가락"],
    tags: ["아침식사", "술안주", "10분이내"],
    steps: ["계란에 소금을 넣고 풉니다.", "팬에 조금씩 부어 말아줍니다.", "먹기 좋게 썰어냅니다."]
  },
  {
    id: "grilled-spam",
    name: "스팸구이",
    ingredients: ["스팸"],
    optional: ["계란", "케첩", "밥"],
    time: 6,
    calories: 340,
    difficulty: "매우 쉬움",
    dishLevel: "적음",
    tools: ["프라이팬", "접시"],
    tags: ["술안주", "설거지적음", "10분이내", "초보자가능"],
    steps: ["스팸을 적당한 두께로 썹니다.", "팬에 앞뒤로 노릇하게 굽습니다.", "밥이나 케첩과 함께 먹습니다."]
  },
  {
    id: "sausage-veggie",
    name: "소시지야채볶음",
    ingredients: ["소시지", "양파", "케첩"],
    optional: ["양배추", "당근", "굴소스"],
    time: 10,
    calories: 420,
    difficulty: "쉬움",
    dishLevel: "보통",
    tools: ["프라이팬", "주걱"],
    tags: ["술안주", "10분이내", "초보자가능"],
    steps: ["소시지와 양파를 먹기 좋게 썹니다.", "팬에 볶다가 케첩을 넣습니다.", "채소가 숨이 죽으면 완성입니다."]
  },
  {
    id: "fishcake-stir-fry",
    name: "어묵볶음",
    ingredients: ["어묵", "간장", "식용유"],
    optional: ["양파", "대파", "고춧가루", "설탕"],
    time: 10,
    calories: 330,
    difficulty: "쉬움",
    dishLevel: "보통",
    tools: ["프라이팬", "주걱"],
    tags: ["술안주", "10분이내", "초보자가능"],
    steps: ["어묵과 양파를 썹니다.", "팬에 볶다가 간장과 설탕을 넣습니다.", "고춧가루를 더하면 매콤해집니다."]
  },
  {
    id: "potato-stir-fry",
    name: "감자볶음",
    ingredients: ["감자", "식용유", "소금"],
    optional: ["당근", "양파", "후추"],
    time: 12,
    calories: 260,
    difficulty: "쉬움",
    dishLevel: "보통",
    tools: ["프라이팬", "주걱"],
    tags: ["초보자가능", "설거지적음"],
    steps: ["감자를 얇게 채 썹니다.", "팬에 기름을 두르고 천천히 볶습니다.", "소금과 후추로 간합니다."]
  },
  {
    id: "bean-sprout-side",
    name: "콩나물무침",
    ingredients: ["콩나물", "소금", "참기름"],
    optional: ["대파", "마늘", "고춧가루"],
    time: 10,
    calories: 130,
    difficulty: "쉬움",
    dishLevel: "적음",
    tools: ["냄비", "그릇"],
    tags: ["10분이내", "초보자가능", "설거지적음"],
    steps: ["콩나물을 짧게 데칩니다.", "소금과 참기름으로 무칩니다.", "대파나 고춧가루를 더합니다."]
  },
  {
    id: "kimchi-tuna-stir",
    name: "김치참치볶음",
    ingredients: ["김치", "참치캔", "식용유"],
    optional: ["양파", "대파", "설탕"],
    time: 8,
    calories: 360,
    difficulty: "쉬움",
    dishLevel: "보통",
    tools: ["프라이팬", "접시"],
    tags: ["술안주", "10분이내", "자취생"],
    steps: ["김치를 잘게 썰어 볶습니다.", "참치를 넣고 함께 볶습니다.", "신맛이 강하면 설탕을 조금 넣습니다."]
  },
  {
    id: "microwave-egg-custard",
    name: "전자레인지 계란찜",
    ingredients: ["계란", "소금", "물"],
    optional: ["대파", "맛살", "참기름"],
    time: 5,
    calories: 170,
    difficulty: "매우 쉬움",
    dishLevel: "적음",
    tools: ["전자레인지", "그릇"],
    tags: ["전자레인지가능", "불안씀", "아침식사", "설거지적음", "10분이내", "초보자가능"],
    steps: ["계란과 물, 소금을 그릇에 섞습니다.", "랩을 느슨하게 덮고 전자레인지에 돌립니다.", "중간에 한 번 저어주면 더 부드럽습니다."]
  },
  {
    id: "microwave-mandu",
    name: "전자레인지 만두",
    ingredients: ["냉동만두"],
    optional: ["간장", "식초", "고춧가루"],
    time: 5,
    calories: 360,
    difficulty: "매우 쉬움",
    dishLevel: "적음",
    tools: ["전자레인지", "접시"],
    tags: ["전자레인지가능", "불안씀", "야식", "설거지적음", "10분이내", "초보자가능"],
    steps: ["접시에 냉동만두를 올립니다.", "물을 살짝 뿌리고 덮개를 씌웁니다.", "전자레인지에 데워 간장과 먹습니다."]
  },
  {
    id: "microwave-cheese-rice",
    name: "전자레인지 치즈밥",
    ingredients: ["밥", "치즈"],
    optional: ["김치", "참치캔", "케첩"],
    time: 5,
    calories: 540,
    difficulty: "매우 쉬움",
    dishLevel: "적음",
    tools: ["전자레인지", "그릇", "숟가락"],
    tags: ["전자레인지가능", "불안씀", "한그릇", "설거지적음", "10분이내", "초보자가능"],
    steps: ["밥 위에 치즈를 올립니다.", "전자레인지에 치즈가 녹을 때까지 돌립니다.", "김치나 케첩을 곁들입니다."]
  },
  {
    id: "bread-pizza",
    name: "식빵 피자",
    ingredients: ["식빵", "치즈", "케첩"],
    optional: ["햄", "양파", "버섯", "소시지"],
    time: 8,
    calories: 380,
    difficulty: "매우 쉬움",
    dishLevel: "적음",
    tools: ["전자레인지", "접시"],
    tags: ["전자레인지가능", "불안씀", "아침식사", "10분이내", "초보자가능"],
    steps: ["식빵에 케첩을 바릅니다.", "치즈와 있는 토핑을 올립니다.", "전자레인지에 치즈가 녹을 때까지 돌립니다."]
  },
  {
    id: "tuna-mayo-toast",
    name: "참치마요토스트",
    ingredients: ["식빵", "참치캔", "마요네즈"],
    optional: ["치즈", "상추", "후추"],
    time: 7,
    calories: 520,
    difficulty: "매우 쉬움",
    dishLevel: "적음",
    tools: ["그릇", "숟가락"],
    tags: ["불안씀", "아침식사", "설거지적음", "10분이내", "초보자가능"],
    steps: ["참치 기름을 빼고 마요네즈와 섞습니다.", "식빵 사이에 참치마요를 넣습니다.", "치즈나 상추를 더해도 좋습니다."]
  },
  {
    id: "kimchi-tofu-stew",
    name: "김치두부찌개",
    ingredients: ["김치", "두부", "물"],
    optional: ["대파", "참치캔", "고춧가루"],
    time: 12,
    calories: 290,
    difficulty: "쉬움",
    dishLevel: "보통",
    tools: ["냄비", "국자"],
    tags: ["자취생", "초보자가능"],
    steps: ["냄비에 김치와 물을 넣고 끓입니다.", "두부를 큼직하게 넣습니다.", "대파나 참치를 넣어 간단히 마무리합니다."]
  },
  {
    id: "doenjang-tofu-soup",
    name: "두부된장국",
    ingredients: ["두부", "된장", "물"],
    optional: ["대파", "애호박", "버섯"],
    time: 10,
    calories: 190,
    difficulty: "쉬움",
    dishLevel: "보통",
    tools: ["냄비", "국자"],
    tags: ["아침식사", "10분이내", "초보자가능"],
    steps: ["물에 된장을 풀어 끓입니다.", "두부를 넣고 한소끔 끓입니다.", "대파나 채소를 넣어 향을 더합니다."]
  },
  {
    id: "kimchi-ramen",
    name: "김치라면",
    ingredients: ["라면", "김치"],
    optional: ["계란", "대파", "고춧가루"],
    time: 8,
    calories: 560,
    difficulty: "매우 쉬움",
    dishLevel: "보통",
    tools: ["냄비", "젓가락"],
    tags: ["야식", "10분이내", "초보자가능"],
    steps: ["라면 물이 끓으면 김치를 먼저 넣습니다.", "면과 스프를 넣고 끓입니다.", "대파나 계란을 더해 마무리합니다."]
  },
  {
    id: "tteok-ramen",
    name: "떡라면",
    ingredients: ["라면", "떡"],
    optional: ["계란", "대파", "치즈"],
    time: 9,
    calories: 720,
    difficulty: "매우 쉬움",
    dishLevel: "보통",
    tools: ["냄비", "젓가락"],
    tags: ["야식", "10분이내", "초보자가능"],
    steps: ["떡을 먼저 넣고 살짝 익힙니다.", "라면을 넣어 함께 끓입니다.", "계란이나 치즈를 올리면 더 든든합니다."]
  },
  {
    id: "cheese-kimchi-rice",
    name: "치즈김치밥",
    ingredients: ["밥", "김치", "치즈"],
    optional: ["참치캔", "스팸", "김"],
    time: 7,
    calories: 590,
    difficulty: "매우 쉬움",
    dishLevel: "적음",
    tools: ["전자레인지", "그릇", "숟가락"],
    tags: ["전자레인지가능", "불안씀", "한그릇", "10분이내", "초보자가능"],
    steps: ["밥 위에 잘게 썬 김치를 올립니다.", "치즈를 덮고 전자레인지에 돌립니다.", "잘 섞어 김과 함께 먹습니다."]
  },
  {
    id: "spam-kimchi-rice",
    name: "스팸김치덮밥",
    ingredients: ["밥", "스팸", "김치"],
    optional: ["계란", "대파", "참기름"],
    time: 10,
    calories: 720,
    difficulty: "쉬움",
    dishLevel: "보통",
    tools: ["프라이팬", "그릇"],
    tags: ["한그릇", "자취생", "10분이내"],
    steps: ["스팸을 굽고 김치를 함께 볶습니다.", "밥 위에 볶은 재료를 올립니다.", "계란프라이를 곁들이면 더 좋습니다."]
  },
  {
    id: "ham-cheese-toast",
    name: "햄치즈토스트",
    ingredients: ["식빵", "햄", "치즈"],
    optional: ["케첩", "마요네즈", "계란"],
    time: 8,
    calories: 430,
    difficulty: "매우 쉬움",
    dishLevel: "적음",
    tools: ["프라이팬", "접시"],
    tags: ["아침식사", "설거지적음", "10분이내", "초보자가능"],
    steps: ["식빵에 햄과 치즈를 올립니다.", "팬에서 앞뒤로 살짝 굽습니다.", "케첩이나 마요네즈를 곁들입니다."]
  },
  {
    id: "egg-toast",
    name: "계란토스트",
    ingredients: ["식빵", "계란"],
    optional: ["치즈", "케첩", "설탕"],
    time: 8,
    calories: 360,
    difficulty: "쉬움",
    dishLevel: "보통",
    tools: ["프라이팬", "접시"],
    tags: ["아침식사", "10분이내", "초보자가능"],
    steps: ["계란을 풀어 팬에 익힙니다.", "식빵 사이에 계란을 넣습니다.", "치즈나 케첩으로 맛을 더합니다."]
  },
  {
    id: "cabbage-egg-stir",
    name: "양배추계란볶음",
    ingredients: ["양배추", "계란", "식용유"],
    optional: ["굴소스", "후추", "대파"],
    time: 10,
    calories: 250,
    difficulty: "쉬움",
    dishLevel: "보통",
    tools: ["프라이팬", "주걱"],
    tags: ["10분이내", "초보자가능", "설거지적음"],
    steps: ["양배추를 채 썰어 볶습니다.", "계란을 넣고 함께 익힙니다.", "굴소스나 후추로 간합니다."]
  },
  {
    id: "mushroom-soy-rice",
    name: "버섯간장덮밥",
    ingredients: ["밥", "버섯", "간장"],
    optional: ["양파", "계란", "참기름"],
    time: 10,
    calories: 430,
    difficulty: "쉬움",
    dishLevel: "보통",
    tools: ["프라이팬", "그릇"],
    tags: ["한그릇", "10분이내", "초보자가능"],
    steps: ["버섯을 먹기 좋게 찢어 볶습니다.", "간장으로 간을 맞춥니다.", "밥 위에 올리고 참기름을 더합니다."]
  },
  {
    id: "potato-egg-bowl",
    name: "감자계란덮밥",
    ingredients: ["밥", "감자", "계란"],
    optional: ["간장", "양파", "후추"],
    time: 13,
    calories: 560,
    difficulty: "쉬움",
    dishLevel: "보통",
    tools: ["프라이팬", "그릇"],
    tags: ["한그릇", "아침식사", "초보자가능"],
    steps: ["감자를 작게 썰어 익을 때까지 볶습니다.", "계란을 넣고 부드럽게 익힙니다.", "밥 위에 올려 간장으로 간합니다."]
  },
  {
    id: "tuna-lettuce-bibimbap",
    name: "참치상추비빔밥",
    ingredients: ["밥", "참치캔", "상추", "고추장"],
    optional: ["계란", "참기름", "김"],
    time: 7,
    calories: 580,
    difficulty: "매우 쉬움",
    dishLevel: "적음",
    tools: ["그릇", "숟가락"],
    tags: ["한그릇", "불안씀", "설거지적음", "10분이내", "초보자가능"],
    steps: ["상추를 손으로 찢어 밥 위에 올립니다.", "참치와 고추장을 넣습니다.", "참기름을 더해 비빕니다."]
  },
  {
    id: "mayo-egg-rice",
    name: "계란마요덮밥",
    ingredients: ["밥", "계란", "마요네즈"],
    optional: ["간장", "김", "대파"],
    time: 8,
    calories: 610,
    difficulty: "쉬움",
    dishLevel: "보통",
    tools: ["프라이팬", "그릇"],
    tags: ["한그릇", "아침식사", "10분이내", "초보자가능"],
    steps: ["계란을 스크램블로 익힙니다.", "밥 위에 계란과 마요네즈를 올립니다.", "간장과 김으로 간을 맞춥니다."]
  },
  {
    id: "microwave-frozen-rice",
    name: "냉동볶음밥 계란업",
    ingredients: ["냉동볶음밥", "계란"],
    optional: ["치즈", "김", "케첩"],
    time: 8,
    calories: 620,
    difficulty: "매우 쉬움",
    dishLevel: "적음",
    tools: ["전자레인지", "그릇"],
    tags: ["전자레인지가능", "한그릇", "설거지적음", "10분이내", "초보자가능"],
    steps: ["냉동볶음밥을 전자레인지에 데웁니다.", "계란을 따로 익히거나 함께 넣어 돌립니다.", "치즈나 김을 올려 먹습니다."]
  },
  {
    id: "frozen-chicken-rice",
    name: "냉동치킨마요덮밥",
    ingredients: ["밥", "냉동치킨", "마요네즈"],
    optional: ["김", "간장", "상추"],
    time: 10,
    calories: 780,
    difficulty: "매우 쉬움",
    dishLevel: "적음",
    tools: ["전자레인지", "그릇"],
    tags: ["전자레인지가능", "한그릇", "야식", "10분이내", "초보자가능"],
    steps: ["냉동치킨을 데워 먹기 좋게 자릅니다.", "밥 위에 치킨과 마요네즈를 올립니다.", "김이나 간장을 더해 비빕니다."]
  },
  {
    id: "bacon-kimchi-fried-rice",
    name: "베이컨김치볶음밥",
    ingredients: ["밥", "베이컨", "김치"],
    optional: ["계란", "대파", "참기름"],
    time: 10,
    calories: 680,
    difficulty: "쉬움",
    dishLevel: "보통",
    tools: ["프라이팬", "주걱"],
    tags: ["한그릇", "자취생", "10분이내"],
    steps: ["베이컨을 먼저 볶아 기름을 냅니다.", "김치를 넣고 볶습니다.", "밥을 넣어 고루 섞습니다."]
  },
  {
    id: "chicken-breast-salad-bowl",
    name: "닭가슴살상추덮밥",
    ingredients: ["밥", "닭가슴살", "상추"],
    optional: ["간장", "마요네즈", "후추"],
    time: 8,
    calories: 520,
    difficulty: "매우 쉬움",
    dishLevel: "적음",
    tools: ["그릇", "숟가락"],
    tags: ["한그릇", "불안씀", "설거지적음", "10분이내", "초보자가능"],
    steps: ["닭가슴살을 먹기 좋게 찢습니다.", "밥 위에 상추와 닭가슴살을 올립니다.", "간장이나 마요네즈로 간합니다."]
  },
  {
    id: "fishcake-soup",
    name: "어묵국",
    ingredients: ["어묵", "물", "간장"],
    optional: ["대파", "무", "후추"],
    time: 10,
    calories: 240,
    difficulty: "쉬움",
    dishLevel: "보통",
    tools: ["냄비", "국자"],
    tags: ["술안주", "10분이내", "초보자가능"],
    steps: ["물을 끓이고 간장으로 간합니다.", "어묵을 넣어 끓입니다.", "대파와 후추를 넣어 마무리합니다."]
  },
  {
    id: "kimchi-mandu-soup",
    name: "김치만두국",
    ingredients: ["냉동만두", "김치", "물"],
    optional: ["계란", "대파", "고춧가루"],
    time: 10,
    calories: 430,
    difficulty: "쉬움",
    dishLevel: "보통",
    tools: ["냄비", "국자"],
    tags: ["야식", "10분이내", "초보자가능"],
    steps: ["김치와 물을 끓입니다.", "냉동만두를 넣고 익힙니다.", "계란이나 대파를 넣어 마무리합니다."]
  },
  {
    id: "tteokbokki-lite",
    name: "초간단 떡볶이",
    ingredients: ["떡", "고추장", "설탕", "물"],
    optional: ["어묵", "대파", "고춧가루"],
    time: 12,
    calories: 520,
    difficulty: "쉬움",
    dishLevel: "보통",
    tools: ["냄비", "주걱"],
    tags: ["야식", "술안주", "초보자가능"],
    steps: ["물에 고추장과 설탕을 풀어 끓입니다.", "떡을 넣고 말랑해질 때까지 끓입니다.", "어묵이나 대파를 더하면 더 맛있습니다."]
  },
  {
    id: "cheese-tteok",
    name: "전자레인지 치즈떡",
    ingredients: ["떡", "치즈"],
    optional: ["케첩", "고추장", "설탕"],
    time: 6,
    calories: 450,
    difficulty: "매우 쉬움",
    dishLevel: "적음",
    tools: ["전자레인지", "그릇"],
    tags: ["전자레인지가능", "불안씀", "야식", "설거지적음", "10분이내", "초보자가능"],
    steps: ["떡에 물을 살짝 뿌려 전자레인지에 데웁니다.", "치즈를 올려 한 번 더 돌립니다.", "케첩이나 고추장소스를 곁들입니다."]
  },
  {
    id: "milk-cheese-ramen",
    name: "우유치즈라면",
    ingredients: ["라면", "우유", "치즈"],
    optional: ["베이컨", "후추", "양파"],
    time: 10,
    calories: 760,
    difficulty: "쉬움",
    dishLevel: "보통",
    tools: ["냄비", "젓가락"],
    tags: ["야식", "10분이내", "초보자가능"],
    steps: ["면을 반쯤 삶아 물을 조금 남깁니다.", "우유와 스프 일부를 넣고 끓입니다.", "치즈를 녹여 부드럽게 마무리합니다."]
  },
  {
    id: "corn-mayo-toast",
    name: "마요치즈토스트",
    ingredients: ["식빵", "마요네즈", "치즈"],
    optional: ["설탕", "햄", "후추"],
    time: 7,
    calories: 420,
    difficulty: "매우 쉬움",
    dishLevel: "적음",
    tools: ["전자레인지", "접시"],
    tags: ["전자레인지가능", "불안씀", "아침식사", "설거지적음", "10분이내", "초보자가능"],
    steps: ["식빵에 마요네즈를 얇게 바릅니다.", "치즈를 올려 전자레인지에 돌립니다.", "후추나 설탕을 살짝 더합니다."]
  },
  {
    id: "seaweed-rice-ball",
    name: "김가루주먹밥",
    ingredients: ["밥", "김", "참기름", "소금"],
    optional: ["참치캔", "마요네즈", "깨"],
    time: 5,
    calories: 390,
    difficulty: "매우 쉬움",
    dishLevel: "적음",
    tools: ["그릇", "위생장갑"],
    tags: ["불안씀", "설거지적음", "아침식사", "10분이내", "초보자가능"],
    steps: ["밥에 김, 참기름, 소금을 넣고 섞습니다.", "먹기 좋은 크기로 뭉칩니다.", "참치마요를 속재료로 넣어도 좋습니다."]
  },
  {
    id: "curry-rice",
    name: "초간단 카레밥",
    ingredients: ["밥", "카레가루", "물"],
    optional: ["감자", "당근", "양파", "닭가슴살"],
    time: 15,
    calories: 560,
    difficulty: "쉬움",
    dishLevel: "보통",
    tools: ["냄비", "국자"],
    tags: ["한그릇", "자취생", "초보자가능"],
    steps: ["물에 카레가루를 풀어 끓입니다.", "있는 채소나 고기를 넣고 익힙니다.", "밥 위에 카레를 부어 먹습니다."]
  },
  {
    id: "tomato-pasta",
    name: "토마토소스 파스타",
    ingredients: ["파스타면", "토마토소스"],
    optional: ["양파", "베이컨", "버섯", "피자치즈"],
    time: 15,
    calories: 610,
    difficulty: "쉬움",
    dishLevel: "보통",
    tools: ["냄비", "프라이팬"],
    tags: ["한그릇", "자취생", "초보자가능"],
    steps: ["파스타면을 삶아 물기를 뺍니다.", "토마토소스를 데워 면과 섞습니다.", "치즈나 베이컨을 더해 마무리합니다."]
  },
  {
    id: "cream-milk-pasta",
    name: "우유크림파스타",
    ingredients: ["파스타면", "우유", "치즈"],
    optional: ["베이컨", "양파", "후추"],
    time: 15,
    calories: 690,
    difficulty: "쉬움",
    dishLevel: "보통",
    tools: ["냄비", "프라이팬"],
    tags: ["한그릇", "자취생", "초보자가능"],
    steps: ["면을 삶아 준비합니다.", "우유와 치즈를 팬에 넣고 약하게 끓입니다.", "면을 넣고 후추로 마무리합니다."]
  },
  {
    id: "soy-butter-pasta",
    name: "간장버터파스타",
    ingredients: ["파스타면", "간장", "버터"],
    optional: ["마늘", "후추", "버섯"],
    time: 12,
    calories: 540,
    difficulty: "쉬움",
    dishLevel: "보통",
    tools: ["냄비", "프라이팬"],
    tags: ["한그릇", "초보자가능"],
    steps: ["파스타면을 삶습니다.", "팬에 버터와 간장을 넣어 소스를 만듭니다.", "면을 넣고 빠르게 볶습니다."]
  },
  {
    id: "tuna-tomato-pasta",
    name: "참치토마토파스타",
    ingredients: ["파스타면", "참치캔", "토마토소스"],
    optional: ["양파", "후추", "치즈"],
    time: 15,
    calories: 680,
    difficulty: "쉬움",
    dishLevel: "보통",
    tools: ["냄비", "프라이팬"],
    tags: ["한그릇", "자취생", "초보자가능"],
    steps: ["면을 삶아 준비합니다.", "토마토소스에 참치를 넣고 데웁니다.", "면과 소스를 섞어 먹습니다."]
  },
  {
    id: "tortilla-pizza",
    name: "또띠아 피자",
    ingredients: ["또띠아", "토마토소스", "피자치즈"],
    optional: ["햄", "소시지", "양파", "버섯"],
    time: 10,
    calories: 520,
    difficulty: "매우 쉬움",
    dishLevel: "적음",
    tools: ["프라이팬", "접시"],
    tags: ["10분이내", "아침식사", "야식", "초보자가능"],
    steps: ["또띠아에 토마토소스를 바릅니다.", "치즈와 토핑을 올립니다.", "팬이나 전자레인지로 치즈를 녹입니다."]
  },
  {
    id: "tortilla-egg-wrap",
    name: "계란또띠아랩",
    ingredients: ["또띠아", "계란", "치즈"],
    optional: ["상추", "햄", "케첩"],
    time: 8,
    calories: 410,
    difficulty: "쉬움",
    dishLevel: "적음",
    tools: ["프라이팬", "접시"],
    tags: ["아침식사", "10분이내", "초보자가능"],
    steps: ["계란을 얇게 익힙니다.", "또띠아에 계란과 치즈를 올립니다.", "돌돌 말아 데워 먹습니다."]
  },
  {
    id: "sweet-potato-cheese",
    name: "전자레인지 고구마치즈",
    ingredients: ["고구마", "치즈"],
    optional: ["우유", "버터", "후추"],
    time: 8,
    calories: 360,
    difficulty: "매우 쉬움",
    dishLevel: "적음",
    tools: ["전자레인지", "그릇"],
    tags: ["전자레인지가능", "불안씀", "아침식사", "설거지적음", "10분이내", "초보자가능"],
    steps: ["고구마를 익혀 으깹니다.", "치즈를 올려 전자레인지에 돌립니다.", "버터나 우유를 조금 넣으면 부드럽습니다."]
  },
  {
    id: "sweet-potato-latte-bowl",
    name: "고구마우유볼",
    ingredients: ["고구마", "우유"],
    optional: ["설탕", "버터", "치즈"],
    time: 7,
    calories: 330,
    difficulty: "매우 쉬움",
    dishLevel: "적음",
    tools: ["그릇", "숟가락"],
    tags: ["불안씀", "아침식사", "설거지적음", "10분이내", "초보자가능"],
    steps: ["익힌 고구마를 그릇에 으깹니다.", "우유를 조금씩 넣어 섞습니다.", "설탕이나 치즈를 더해 먹습니다."]
  },
  {
    id: "cucumber-tuna-salad",
    name: "오이참치샐러드",
    ingredients: ["오이", "참치캔", "마요네즈"],
    optional: ["후추", "상추", "옥수수콘"],
    time: 5,
    calories: 310,
    difficulty: "매우 쉬움",
    dishLevel: "적음",
    tools: ["그릇", "숟가락"],
    tags: ["불안씀", "설거지적음", "10분이내", "초보자가능"],
    steps: ["오이를 얇게 썹니다.", "참치와 마요네즈를 섞습니다.", "오이에 올리거나 함께 버무립니다."]
  },
  {
    id: "tomato-egg-stir",
    name: "토마토계란볶음",
    ingredients: ["토마토", "계란", "식용유"],
    optional: ["소금", "후추", "대파"],
    time: 8,
    calories: 260,
    difficulty: "쉬움",
    dishLevel: "보통",
    tools: ["프라이팬", "주걱"],
    tags: ["아침식사", "10분이내", "초보자가능"],
    steps: ["계란을 먼저 부드럽게 익혀 덜어둡니다.", "토마토를 볶다가 계란을 다시 넣습니다.", "소금과 후추로 간합니다."]
  },
  {
    id: "spinach-egg-rice",
    name: "시금치계란덮밥",
    ingredients: ["밥", "시금치", "계란"],
    optional: ["간장", "참기름", "김"],
    time: 10,
    calories: 500,
    difficulty: "쉬움",
    dishLevel: "보통",
    tools: ["프라이팬", "그릇"],
    tags: ["한그릇", "아침식사", "10분이내", "초보자가능"],
    steps: ["시금치를 살짝 볶습니다.", "계란을 넣어 함께 익힙니다.", "밥 위에 올리고 간장으로 간합니다."]
  },
  {
    id: "broccoli-cheese-bowl",
    name: "브로콜리치즈밥",
    ingredients: ["밥", "브로콜리", "치즈"],
    optional: ["우유", "후추", "닭가슴살"],
    time: 10,
    calories: 520,
    difficulty: "매우 쉬움",
    dishLevel: "적음",
    tools: ["전자레인지", "그릇"],
    tags: ["전자레인지가능", "한그릇", "10분이내", "초보자가능"],
    steps: ["브로콜리를 작게 잘라 데우거나 익힙니다.", "밥과 치즈를 함께 올립니다.", "전자레인지에 치즈가 녹을 때까지 돌립니다."]
  },
  {
    id: "paprika-sausage-stir",
    name: "파프리카소시지볶음",
    ingredients: ["파프리카", "소시지", "케첩"],
    optional: ["양파", "굴소스", "후추"],
    time: 10,
    calories: 390,
    difficulty: "쉬움",
    dishLevel: "보통",
    tools: ["프라이팬", "주걱"],
    tags: ["술안주", "10분이내", "초보자가능"],
    steps: ["파프리카와 소시지를 썹니다.", "팬에 볶다가 케첩을 넣습니다.", "양파나 굴소스로 맛을 더합니다."]
  },
  {
    id: "perilla-tuna-rice",
    name: "깻잎참치비빔밥",
    ingredients: ["밥", "깻잎", "참치캔", "고추장"],
    optional: ["참기름", "김", "계란"],
    time: 7,
    calories: 570,
    difficulty: "매우 쉬움",
    dishLevel: "적음",
    tools: ["그릇", "숟가락"],
    tags: ["한그릇", "불안씀", "10분이내", "초보자가능"],
    steps: ["깻잎을 잘게 찢어 밥 위에 올립니다.", "참치와 고추장을 넣습니다.", "참기름을 더해 비빕니다."]
  },
  {
    id: "sookju-beefless-stir",
    name: "숙주굴소스볶음",
    ingredients: ["숙주", "굴소스", "식용유"],
    optional: ["소시지", "베이컨", "대파", "후추"],
    time: 8,
    calories: 210,
    difficulty: "쉬움",
    dishLevel: "보통",
    tools: ["프라이팬", "주걱"],
    tags: ["술안주", "10분이내", "초보자가능"],
    steps: ["팬에 기름을 두르고 숙주를 빠르게 볶습니다.", "굴소스를 넣어 간합니다.", "소시지나 베이컨을 더해도 좋습니다."]
  },
  {
    id: "buchu-pancake-lite",
    name: "초간단 부추전",
    ingredients: ["부추", "계란", "식용유"],
    optional: ["소금", "양파", "간장"],
    time: 12,
    calories: 290,
    difficulty: "쉬움",
    dishLevel: "보통",
    tools: ["프라이팬", "뒤집개"],
    tags: ["술안주", "초보자가능"],
    steps: ["부추를 먹기 좋게 썹니다.", "계란과 소금을 섞어 반죽처럼 만듭니다.", "팬에 넓게 부쳐 간장과 먹습니다."]
  },
  {
    id: "seaweed-soup",
    name: "초간단 미역국",
    ingredients: ["미역", "간장", "물"],
    optional: ["참기름", "두부", "참치캔"],
    time: 10,
    calories: 120,
    difficulty: "쉬움",
    dishLevel: "보통",
    tools: ["냄비", "국자"],
    tags: ["아침식사", "10분이내", "초보자가능"],
    steps: ["미역을 불려 냄비에 넣습니다.", "물과 간장을 넣고 끓입니다.", "참기름이나 두부를 더해 마무리합니다."]
  },
  {
    id: "tofu-miso-rice",
    name: "된장두부덮밥",
    ingredients: ["밥", "두부", "된장"],
    optional: ["대파", "참기름", "고춧가루"],
    time: 10,
    calories: 460,
    difficulty: "쉬움",
    dishLevel: "보통",
    tools: ["프라이팬", "그릇"],
    tags: ["한그릇", "10분이내", "초보자가능"],
    steps: ["두부를 으깨 팬에 볶습니다.", "된장을 조금 넣어 간합니다.", "밥 위에 올려 비벼 먹습니다."]
  },
  {
    id: "ssamjang-lettuce-rice",
    name: "쌈장상추비빔밥",
    ingredients: ["밥", "상추", "쌈장"],
    optional: ["참치캔", "계란", "참기름"],
    time: 5,
    calories: 430,
    difficulty: "매우 쉬움",
    dishLevel: "적음",
    tools: ["그릇", "숟가락"],
    tags: ["한그릇", "불안씀", "설거지적음", "10분이내", "초보자가능"],
    steps: ["상추를 손으로 찢어 밥 위에 올립니다.", "쌈장과 참기름을 넣습니다.", "있는 단백질을 더해 비빕니다."]
  },
  {
    id: "mackerel-kimchi-stew",
    name: "고등어김치조림",
    ingredients: ["고등어캔", "김치", "물"],
    optional: ["대파", "고춧가루", "설탕"],
    time: 12,
    calories: 420,
    difficulty: "쉬움",
    dishLevel: "보통",
    tools: ["냄비", "국자"],
    tags: ["자취생", "초보자가능"],
    steps: ["김치와 물을 냄비에 넣고 끓입니다.", "고등어캔을 넣어 더 끓입니다.", "대파나 고춧가루로 마무리합니다."]
  },
  {
    id: "saury-kimchi-rice",
    name: "꽁치김치덮밥",
    ingredients: ["밥", "꽁치캔", "김치"],
    optional: ["대파", "고춧가루", "참기름"],
    time: 10,
    calories: 620,
    difficulty: "쉬움",
    dishLevel: "보통",
    tools: ["프라이팬", "그릇"],
    tags: ["한그릇", "자취생", "10분이내"],
    steps: ["김치를 팬에 볶습니다.", "꽁치캔을 넣고 살짝 으깨 볶습니다.", "밥 위에 올려 먹습니다."]
  },
  {
    id: "golbaengi-noodle",
    name: "골뱅이비빔국수",
    ingredients: ["국수", "골뱅이캔", "고추장"],
    optional: ["오이", "상추", "참기름", "식초"],
    time: 12,
    calories: 560,
    difficulty: "쉬움",
    dishLevel: "보통",
    tools: ["냄비", "그릇"],
    tags: ["술안주", "야식", "초보자가능"],
    steps: ["국수를 삶아 찬물에 헹굽니다.", "고추장과 참기름으로 양념합니다.", "골뱅이와 채소를 넣고 비빕니다."]
  },
  {
    id: "corn-cheese",
    name: "전자레인지 콘치즈",
    ingredients: ["옥수수콘", "마요네즈", "치즈"],
    optional: ["설탕", "후추", "피자치즈"],
    time: 6,
    calories: 420,
    difficulty: "매우 쉬움",
    dishLevel: "적음",
    tools: ["전자레인지", "그릇"],
    tags: ["전자레인지가능", "불안씀", "술안주", "설거지적음", "10분이내", "초보자가능"],
    steps: ["옥수수콘 물기를 빼고 그릇에 담습니다.", "마요네즈와 치즈를 올립니다.", "전자레인지에 치즈가 녹을 때까지 돌립니다."]
  },
  {
    id: "corn-mayo-rice",
    name: "콘마요덮밥",
    ingredients: ["밥", "옥수수콘", "마요네즈"],
    optional: ["참치캔", "김", "후추"],
    time: 5,
    calories: 560,
    difficulty: "매우 쉬움",
    dishLevel: "적음",
    tools: ["그릇", "숟가락"],
    tags: ["한그릇", "불안씀", "설거지적음", "10분이내", "초보자가능"],
    steps: ["밥 위에 옥수수콘을 올립니다.", "마요네즈와 후추를 더합니다.", "김이나 참치를 곁들여 비빕니다."]
  },
  {
    id: "chili-shrimp-rice",
    name: "칠리새우덮밥",
    ingredients: ["밥", "냉동새우", "칠리소스"],
    optional: ["양파", "파프리카", "계란"],
    time: 12,
    calories: 590,
    difficulty: "쉬움",
    dishLevel: "보통",
    tools: ["프라이팬", "그릇"],
    tags: ["한그릇", "자취생", "초보자가능"],
    steps: ["냉동새우를 팬에 익힙니다.", "칠리소스를 넣어 볶습니다.", "밥 위에 새우를 올립니다."]
  },
  {
    id: "shrimp-fried-rice",
    name: "새우볶음밥",
    ingredients: ["밥", "냉동새우", "식용유"],
    optional: ["계란", "대파", "굴소스"],
    time: 10,
    calories: 580,
    difficulty: "쉬움",
    dishLevel: "보통",
    tools: ["프라이팬", "주걱"],
    tags: ["한그릇", "10분이내", "초보자가능"],
    steps: ["새우를 팬에 먼저 익힙니다.", "밥과 기름을 넣고 볶습니다.", "굴소스나 계란으로 맛을 더합니다."]
  },
  {
    id: "duck-lettuce-rice",
    name: "훈제오리상추덮밥",
    ingredients: ["밥", "훈제오리", "상추"],
    optional: ["쌈장", "깻잎", "마요네즈"],
    time: 8,
    calories: 680,
    difficulty: "매우 쉬움",
    dishLevel: "적음",
    tools: ["전자레인지", "그릇"],
    tags: ["전자레인지가능", "한그릇", "10분이내", "초보자가능"],
    steps: ["훈제오리를 데웁니다.", "밥 위에 상추와 오리를 올립니다.", "쌈장이나 마요네즈로 간합니다."]
  },
  {
    id: "frozen-potato-cheese",
    name: "치즈감자튀김",
    ingredients: ["냉동감자", "치즈"],
    optional: ["케첩", "마요네즈", "후추"],
    time: 10,
    calories: 520,
    difficulty: "매우 쉬움",
    dishLevel: "적음",
    tools: ["전자레인지", "접시"],
    tags: ["전자레인지가능", "야식", "술안주", "설거지적음", "10분이내", "초보자가능"],
    steps: ["냉동감자를 데우거나 굽습니다.", "치즈를 올려 한 번 더 데웁니다.", "케첩과 함께 먹습니다."]
  },
  {
    id: "bean-rice-bowl",
    name: "콩간장밥",
    ingredients: ["밥", "콩", "간장"],
    optional: ["참기름", "김", "계란"],
    time: 5,
    calories: 480,
    difficulty: "매우 쉬움",
    dishLevel: "적음",
    tools: ["그릇", "숟가락"],
    tags: ["한그릇", "불안씀", "아침식사", "설거지적음", "10분이내", "초보자가능"],
    steps: ["밥 위에 콩을 올립니다.", "간장과 참기름을 넣습니다.", "김을 부숴 넣고 비빕니다."]
  },
  {
    id: "bean-tofu-salad",
    name: "콩두부샐러드",
    ingredients: ["콩", "두부", "간장"],
    optional: ["상추", "오이", "참기름"],
    time: 7,
    calories: 320,
    difficulty: "매우 쉬움",
    dishLevel: "적음",
    tools: ["그릇", "숟가락"],
    tags: ["불안씀", "설거지적음", "10분이내", "초보자가능"],
    steps: ["두부를 먹기 좋게 자릅니다.", "콩과 채소를 함께 담습니다.", "간장과 참기름을 뿌립니다."]
  },
  {
    id: "mustard-ham-toast",
    name: "머스타드햄토스트",
    ingredients: ["식빵", "햄", "머스타드"],
    optional: ["치즈", "상추", "토마토"],
    time: 6,
    calories: 390,
    difficulty: "매우 쉬움",
    dishLevel: "적음",
    tools: ["접시"],
    tags: ["불안씀", "아침식사", "설거지적음", "10분이내", "초보자가능"],
    steps: ["식빵에 머스타드를 바릅니다.", "햄과 있는 재료를 올립니다.", "그대로 먹거나 살짝 데웁니다."]
  },
  {
    id: "chili-sausage-wrap",
    name: "칠리소시지랩",
    ingredients: ["또띠아", "소시지", "칠리소스"],
    optional: ["상추", "양파", "치즈"],
    time: 8,
    calories: 520,
    difficulty: "매우 쉬움",
    dishLevel: "적음",
    tools: ["프라이팬", "접시"],
    tags: ["야식", "10분이내", "초보자가능"],
    steps: ["소시지를 데우거나 굽습니다.", "또띠아에 소시지와 칠리소스를 올립니다.", "채소와 함께 말아 먹습니다."]
  },
  {
    id: "cabbage-tuna-mayo",
    name: "양배추참치마요",
    ingredients: ["양배추", "참치캔", "마요네즈"],
    optional: ["후추", "옥수수콘", "식빵"],
    time: 6,
    calories: 350,
    difficulty: "매우 쉬움",
    dishLevel: "적음",
    tools: ["그릇", "숟가락"],
    tags: ["불안씀", "설거지적음", "10분이내", "초보자가능"],
    steps: ["양배추를 얇게 채 썹니다.", "참치와 마요네즈를 섞습니다.", "양배추와 함께 버무려 먹습니다."]
  },
  {
    id: "cabbage-rice-bowl",
    name: "양배추덮밥",
    ingredients: ["밥", "양배추", "간장"],
    optional: ["계란", "굴소스", "후추"],
    time: 10,
    calories: 450,
    difficulty: "쉬움",
    dishLevel: "보통",
    tools: ["프라이팬", "그릇"],
    tags: ["한그릇", "10분이내", "초보자가능"],
    steps: ["양배추를 채 썰어 볶습니다.", "간장이나 굴소스로 간합니다.", "밥 위에 올리고 계란을 곁들입니다."]
  },
  {
    id: "zucchini-egg-stir",
    name: "애호박계란볶음",
    ingredients: ["애호박", "계란", "식용유"],
    optional: ["소금", "대파", "후추"],
    time: 9,
    calories: 240,
    difficulty: "쉬움",
    dishLevel: "보통",
    tools: ["프라이팬", "주걱"],
    tags: ["아침식사", "10분이내", "초보자가능"],
    steps: ["애호박을 얇게 썰어 볶습니다.", "계란을 넣고 함께 익힙니다.", "소금과 후추로 간합니다."]
  },
  {
    id: "mushroom-cream-rice",
    name: "버섯크림밥",
    ingredients: ["밥", "버섯", "우유", "치즈"],
    optional: ["양파", "후추", "베이컨"],
    time: 12,
    calories: 610,
    difficulty: "쉬움",
    dishLevel: "보통",
    tools: ["프라이팬", "그릇"],
    tags: ["한그릇", "자취생", "초보자가능"],
    steps: ["버섯을 볶습니다.", "우유와 치즈를 넣어 소스를 만듭니다.", "밥을 넣어 리조또처럼 섞습니다."]
  },
  {
    id: "kimchi-oil-noodle",
    name: "김치들기름풍 비빔면",
    ingredients: ["라면", "김치", "참기름"],
    optional: ["김", "계란", "설탕"],
    time: 8,
    calories: 540,
    difficulty: "매우 쉬움",
    dishLevel: "적음",
    tools: ["냄비", "그릇"],
    tags: ["야식", "10분이내", "초보자가능"],
    steps: ["라면 면만 삶아 찬물에 헹굽니다.", "김치와 참기름을 넣습니다.", "김을 부숴 넣고 비빕니다."]
  },
  {
    id: "soy-mayo-noodle",
    name: "간장마요비빔면",
    ingredients: ["라면", "간장", "마요네즈"],
    optional: ["계란", "김", "참기름"],
    time: 7,
    calories: 610,
    difficulty: "매우 쉬움",
    dishLevel: "적음",
    tools: ["냄비", "그릇"],
    tags: ["야식", "10분이내", "초보자가능"],
    steps: ["라면 면만 삶아 물기를 뺍니다.", "간장과 마요네즈를 섞습니다.", "김이나 계란을 올려 먹습니다."]
  },
  {
    id: "potato-curry-stir",
    name: "카레감자볶음",
    ingredients: ["감자", "카레가루", "식용유"],
    optional: ["양파", "당근", "후추"],
    time: 12,
    calories: 300,
    difficulty: "쉬움",
    dishLevel: "보통",
    tools: ["프라이팬", "주걱"],
    tags: ["초보자가능", "설거지적음"],
    steps: ["감자를 얇게 썰어 볶습니다.", "카레가루를 뿌려 간합니다.", "양파를 더하면 단맛이 좋아집니다."]
  },
  {
    id: "mayo-crab-toast",
    name: "맛살마요토스트",
    ingredients: ["식빵", "맛살", "마요네즈"],
    optional: ["치즈", "오이", "후추"],
    time: 7,
    calories: 430,
    difficulty: "매우 쉬움",
    dishLevel: "적음",
    tools: ["그릇", "접시"],
    tags: ["불안씀", "아침식사", "설거지적음", "10분이내", "초보자가능"],
    steps: ["맛살을 찢어 마요네즈와 섞습니다.", "식빵 사이에 넣습니다.", "치즈나 오이를 더해도 좋습니다."]
  },
  {
    id: "crab-egg-rice",
    name: "맛살계란덮밥",
    ingredients: ["밥", "맛살", "계란"],
    optional: ["간장", "대파", "참기름"],
    time: 9,
    calories: 520,
    difficulty: "쉬움",
    dishLevel: "보통",
    tools: ["프라이팬", "그릇"],
    tags: ["한그릇", "아침식사", "10분이내", "초보자가능"],
    steps: ["맛살을 찢고 계란과 함께 익힙니다.", "간장으로 간을 맞춥니다.", "밥 위에 올려 먹습니다."]
  },
  {
    id: "cold-tofu-kimchi",
    name: "두부김치무침",
    ingredients: ["두부", "김치", "참기름"],
    optional: ["참치캔", "깨", "대파"],
    time: 5,
    calories: 280,
    difficulty: "매우 쉬움",
    dishLevel: "적음",
    tools: ["접시", "숟가락"],
    tags: ["불안씀", "술안주", "설거지적음", "10분이내", "초보자가능"],
    steps: ["두부를 먹기 좋게 자릅니다.", "김치에 참기름을 넣어 섞습니다.", "두부 위에 김치를 올립니다."]
  },
  {
    id: "microwave-curry-rice",
    name: "전자레인지 카레밥",
    ingredients: ["밥", "카레가루", "물"],
    optional: ["당근", "양파", "치즈", "닭가슴살"],
    time: 8,
    calories: 520,
    difficulty: "매우 쉬움",
    dishLevel: "적음",
    tools: ["전자레인지", "그릇"],
    tags: ["전자레인지가능", "한그릇", "설거지적음", "10분이내", "초보자가능"],
    steps: ["그릇에 물과 카레가루를 섞습니다.", "밥과 잘게 썬 채소를 넣고 전자레인지에 돌립니다.", "중간에 한 번 저어 마무리합니다."]
  }
];
